### ISSUE TITLE
create a new vue app by vite , dev cmd error

### ISSUE THREAD

**Issue by kvchen95** [bluwy/vite-plugin-warmup#2]
```shell
pnpm dev

failed to load config from /Users/sanchen/Common/my-vue-app/vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/sanchen/Common/my-vue-app/node_modules/.pnpm/registry.npmmirror.com+vite-plugin-warmup@0.0.3_vite@4.3.1/node_modules/vite-plugin-warmup/index.js from /Users/sanchen/Common/my-vue-app/vite.config.ts not supported.
Instead change the require of index.js in /Users/sanchen/Common/my-vue-app/vite.config.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/sanchen/Common/my-vue-app/vite.config.ts:33:44)
    at Object.require.extensions.<computed> [as .ts] (/Users/sanchen/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:68710:20)
    at loadConfigFromBundledFile (/Users/sanchen/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:68718:17)
    at loadConfigFromFile (/Users/sanchen/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:68637:32)
    at async resolveConfig (/Users/sanchen/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:68185:28)
    at async createServer (/Users/sanchen/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66699:20)
    at async CAC.<anonymous> (/Users/sanchen/.config/yarn/global/node_modules/vite/dist/node/cli.js:687:24)
 ERROR  Command failed with exit code 1.
```
device: Mac mini 2018
system: macOS Ventura 13.2
pnpm: 6.14.6
node: v16.9.1

package.json
```json
{
  "name": "my-vue-app",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "run-p type-check build-only",
    "preview": "vite preview",
    "test:unit": "vitest",
    "test:e2e": "start-server-and-test preview http://localhost:4173 'cypress run --e2e'",
    "test:e2e:dev": "start-server-and-test 'vite dev --port 4173' http://localhost:4173 'cypress open --e2e'",
    "build-only": "vite build",
    "type-check": "vue-tsc --noEmit -p tsconfig.vitest.json --composite false",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore",
    "format": "prettier --write src/"
  },
  "dependencies": {
    "pinia": "^2.0.32",
    "vue": "^3.2.47",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.2.0",
    "@types/jsdom": "^21.1.0",
    "@types/node": "^18.14.2",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vitejs/plugin-vue-jsx": "^3.0.0",
    "@vue/eslint-config-prettier": "^7.1.0",
    "@vue/eslint-config-typescript": "^11.0.2",
    "@vue/test-utils": "^2.3.0",
    "@vue/tsconfig": "^0.1.3",
    "cypress": "^12.7.0",
    "eslint": "^8.34.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-vue": "^9.9.0",
    "jsdom": "^21.1.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.8.4",
    "start-server-and-test": "^2.0.0",
    "typescript": "~4.8.4",
    "vite": "^4.3.1",
    "vite-plugin-warmup": "^0.0.3",
    "vitest": "^0.29.1",
    "vue-tsc": "^1.2.0"
  }
}
```
vite.config.ts
```typescript
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import { warmup } from 'vite-plugin-warmup'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueJsx(),
    warmup({
      // warm up the files and its imported JS modules recursively
      clientFiles: ['./**/*.html', './src/components/*.jsx']
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```

**Comment by bluwy** [comment]
`vite-plugin-warmup` is ESM only, so you'd need to use `"type": "module"` in the `package.json`, or use `vite.config.mts`
